# -*- coding: utf-8 -*-
"""app
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/16gW4FijDtLhFvXKEszsGFFbm83PYFFSf
"""

import streamlit as st
import pandas as pd
import torch
import numpy as np
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.metrics.pairwise import cosine_similarity
from huggingface_hub import hf_hub_download

# =========================
# CONFIG
# =========================
st.set_page_config(
    page_title="Coffee Recommender",
    layout="wide"
)

# Parameter sesuai Bab IV penelitian [cite: 585, 920]
ALPHA = 0.7   
TOP_N = 5
MAX_LEN = 320 # Sesuai cek.pdf hal 40 & 42 [cite: 754, 788, 828]

# =========================
# LOAD ASSETS
# =========================
@st.cache_resource
def load_assets():
    REPO_ID = "lattezice/cafe-sentimen-bert"
    
    with st.spinner("Mengunduh aset dari Hugging Face..."):
        # 1. Download Dataset
        csv_path = hf_hub_download(repo_id=REPO_ID, filename="processed_coffee.csv")
        df = pd.read_csv(csv_path)

        # 2. Download model
        try:
            model_path = hf_hub_download(repo_id=REPO_ID, filename="best_model.pt")
        except:
            model_path = hf_hub_download(repo_id=REPO_ID, filename="models/best_model.pt")

        # 3. Download precomputed assets (.npy)
        emb_path = hf_hub_download(repo_id=REPO_ID, filename="cafe_embedding.npy")
        sent_path = hf_hub_download(repo_id=REPO_ID, filename="sentiment_score.npy")
        
        cafe_emb = np.load(emb_path)      
        sentiment_score = np.load(sent_path)

    # Inisialisasi Model (3 label: 0=Positif, 1=Netral, 2=Negatif) [cite: 801, 816]
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=3)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    state_dict = torch.load(model_path, map_location=device)
    model.load_state_dict(state_dict, strict=False)
    model.to(device)
    model.eval()

    return df, tokenizer, model, cafe_emb, sentiment_score, device

# Eksekusi Load
try:
    df, tokenizer, model, cafe_emb_matrix, sentiment_score_vec, device = load_assets()
except Exception as e:
    st.error(f"Gagal memuat assets: {e}")
    st.stop()

# =========================
# HELPER FUNCTION
# =========================
def encode_text(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN
    ).to(device)

    with torch.no_grad():
        outputs = model.bert(**inputs) 
        # Mengambil [CLS] token sebagai representasi ulasan [cite: 499, 869]
        emb = outputs.last_hidden_state[:, 0, :]  

    return emb.cpu().numpy().flatten()

# =========================
# UI
# =========================
st.title("☕ Coffee Recommender")
st.markdown("Sistem Rekomendasi Café Berbasis Embedding & Sentimen")

with st.form("recommender_form"):
    user_text = st.text_area(
        "Preferensi Café (contoh: cozy quiet place for studying)",
        height=120
    )

    col1, col2 = st.columns(2)
    with col1:
        city = st.selectbox("City", sorted(df["city"].dropna().unique()))
    with col2:
        state = st.selectbox("State", sorted(df["state"].dropna().unique()))

    submitted = st.form_submit_button("Cari Rekomendasi")

# =========================
# RECOMMENDATION LOGIC (VERSI BERSIH)
# =========================
if submitted:
    if user_text.strip() == "":
        st.warning("Masukkan preferensi café terlebih dahulu.")
    else:
        with st.spinner("Menganalisis preferensi..."):
            # 1. Encode user preference (BERT CLS Token)
            user_emb = encode_text(user_text).reshape(1, -1)

            # 2. Similarity & Hybrid Scoring (Alpha 0.7 sesuai cek.pdf)
            similarity_scores = cosine_similarity(user_emb, cafe_emb_matrix)[0]
            hybrid_scores = (ALPHA * similarity_scores) + ((1 - ALPHA) * sentiment_score_vec)

            # 3. Sinkronisasi Data
            result_df = df.drop_duplicates("business_id").copy()
            min_len = min(len(result_df), len(hybrid_scores))
            result_df = result_df.iloc[:min_len].copy()
            result_df["hybrid_score"] = hybrid_scores[:min_len]

            # 4. Filter Lokasi
            final_res = result_df[
                (result_df["city"].str.lower() == city.lower()) &
                (result_df["state"].str.lower() == state.lower())
            ].copy()

            if final_res.empty:
                st.error(f"Tidak ada café ditemukan di {city}, {state}.")
            else:
                # --- PERBAIKAN RATING & RANKING ---
                final_res = final_res.sort_values("hybrid_score", ascending=False).head(TOP_N)
                
                # Membulatkan rating menjadi 1 angka di belakang koma (misal: 4.0)
                final_res["cafe_rating"] = final_res["cafe_rating"].round(1)
                
                # Membulatkan hybrid_score menjadi 3 angka di belakang koma agar rapi
                final_res["hybrid_score"] = final_res["hybrid_score"].round(3)
                
                # Menambahkan kolom Ranking (1-5)
                final_res.insert(0, "Rank", range(1, 1 + len(final_res)))

                # --- OUTPUT TUNGGAL ---
                st.subheader("🎯 Hasil Rekomendasi Terbaik")
                
                # Kolom yang ditampilkan sesuai permintaan UI/UX
                display_cols = ["Rank", "cafe_name", "cafe_rating", "city", "state", "hybrid_score"]
                
                # Mengganti nama kolom agar lebih rapi di tampilan
                final_res.columns = ["Rank", "Nama Café", "Rating", "Kota", "State", "Match Score"]
                
                # Tampilkan hanya satu tabel di sini
                st.table(final_res.reset_index(drop=True))
                
                st.success(f"Berhasil menemukan café yang paling cocok dengan preferensi Anda!")

# PENTING: Pastikan setelah baris ini (di luar blok 'if submitted') 
# TIDAK ADA lagi perintah st.write(df) atau st.table(df).
